const List<Map<String, dynamic>> countryList = [
  {
    "code": "NG",
    "name": "Nigeria",
    "country": "Nigeria",
    "currency": "NGN",
    "currency_sign": "₦",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "GH",
    "name": "Ghana",
    "country": "Ghana",
    "currency": "GHS",
    "currency_sign": "₵",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "KE",
    "name": "Kenya",
    "country": "Kenya",
    "currency": "KES",
    "currency_sign": "KSh",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "UG",
    "name": "Uganda",
    "country": "Uganda",
    "currency": "UGX",
    "currency_sign": "USh",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "TZ",
    "name": "Tanzania",
    "country": "Tanzania",
    "currency": "TZS",
    "currency_sign": "TSh",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "MW",
    "name": "Malawi",
    "country": "Malawi",
    "currency": "MWK",
    "currency_sign": "MK",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "RW",
    "name": "Rwanda",
    "country": "Rwanda",
    "currency": "RWF",
    "currency_sign": "R₣",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "SL",
    "name": "Sierra Leone",
    "country": "Sierra Leone",
    "currency": "SLL",
    "currency_sign": "Le",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "ZM",
    "name": "Zambia",
    "country": "Zambia",
    "currency": "ZMW",
    "currency_sign": "ZK",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "SN",
    "name": "Senegal",
    "country": "Senegal",
    "currency": "XOF",
    "currency_sign": "CFA",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "CI",
    "name": "Côte d'Ivoire",
    "country": "Côte d'Ivoire",
    "currency": "XOF",
    "currency_sign": "CFA",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "CM",
    "name": "Cameroon",
    "country": "Cameroon",
    "currency": "XAF",
    "currency_sign": "FCFA",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "BF",
    "name": "Burkina Faso",
    "country": "Burkina Faso",
    "currency": "XOF",
    "currency_sign": "CFA",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "ET",
    "name": "Ethiopia",
    "country": "Ethiopia",
    "currency": "ETB",
    "currency_sign": "Br",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "EG",
    "name": "Egypt",
    "country": "Egypt",
    "currency": "EGP",
    "currency_sign": "£E",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "ZA",
    "name": "South Africa",
    "country": "South Africa",
    "currency": "ZAR",
    "currency_sign": "R",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "INT_USD",
    "name": "International (USD)",
    "country": "International",
    "currency": "USD",
    "currency_sign": "\$",
    "routing_number": true,
    "swift_code": true,
  },
  {
    "code": "INT_EUR",
    "name": "International (EUR)",
    "country": "International",
    "currency": "EUR",
    "currency_sign": "€",
    "routing_number": true,
    "swift_code": true,
  },
  {
    "code": "INT_GBP",
    "name": "International (GBP)",
    "country": "International",
    "currency": "GBP",
    "currency_sign": "£",
    "routing_number": true,
    "swift_code": true,
  },
];
