const List<Map<String, dynamic>> countryList = [
  {
    "code": "NG",
    "name": "Nigeria",
    "routing_number": false,
    "swift_code": false,
  },
  {"code": "GH", "name": "Ghana", "routing_number": false, "swift_code": false},
  {"code": "KE", "name": "Kenya", "routing_number": false, "swift_code": false},
  {
    "code": "UG",
    "name": "Uganda",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "TZ",
    "name": "Tanzania",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "MW",
    "name": "Malawi",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "RW",
    "name": "Rwanda",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "SL",
    "name": "Sierra Leone",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "ZM",
    "name": "Zambia",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "SN",
    "name": "Senegal",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "CI",
    "name": "Côte d'Ivoire",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "CM",
    "name": "Cameroon",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "BF",
    "name": "Burkina Faso",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "ET",
    "name": "Ethiopia",
    "routing_number": false,
    "swift_code": false,
  },
  {"code": "EG", "name": "Egypt", "routing_number": false, "swift_code": false},
  {
    "code": "ZA",
    "name": "South Africa",
    "routing_number": false,
    "swift_code": false,
  },
  {
    "code": "INT_USD",
    "name": "International (USD)",
    "routing_number": true,
    "swift_code": true,
  },
  {
    "code": "INT_EUR",
    "name": "International (EUR)",
    "routing_number": true,
    "swift_code": true,
  },
  {
    "code": "INT_GBP",
    "name": "International (GBP)",
    "routing_number": true,
    "swift_code": true,
  },
];
